[package]
name = "pks_ruby"
version = "0.1.0"
edition = "2021"
authors = ["murny <1930474+murny@users.noreply.github.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6.2" }
